services:
  - type: web
    name: bodydouble-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: PORT
        generateValue: true
      - key: NODE_ENV
        value: production
